name: Executing Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  packages: read

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build docker image
      run: docker build --build-arg GH_USERNAME=${{ secrets.GH_USERNAME }} --build-arg GH_TOKEN=${{ secrets.GITHUB_TOKEN }} -t ${{ secrets.DOCKER_HUB_USERNAME }}/pipedriverepository:${{ github.sha }} .
    - name: Docker push
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pipedriverepository:${{ github.sha }}
      
  test:
    runs-on: ubuntu-latest
    needs: 
      - docker_build
    container:
      image: rasangikaw/pipedriverepository:${{ github.sha }}
    steps: 
    - name: execute test
      run: |
           env
           cd /usr/src/app
           pwd && ls -al
           mvn clean test -s settings.xml -P PROD -Dsurefire.suiteXmlFiles="pipeDriveDealVerificationSuite.xml"
